services:
  # backend:
  #   build:
  #     context: backend
  #   env_file:
  #     - backend/Docker.env
  #   ports:
  #     - 8000:8000

  mongodb:
    image: mongo:7.0.34
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cr3t
    volumes:
      - .volumes/mongo:/data/db
