include:
  - https://github.com/hansen-young/dev-stack.git#main:mongodb/compose.yml
  - https://github.com/hansen-young/dev-stack.git#main:valkey/compose.yml
  
services:
  # backend:
  #   build:
  #     context: backend
  #   env_file:
  #     - backend/Docker.env
  #   ports:
  #     - 8000:8000

  searxng:
    image: searxng/searxng:2026.5.29-4ea5c57a8
    ports:
      - 5279:8080
    environment:
      SEARXNG_BIND_ADDRESS: 0.0.0.0
      SEARXNG_PORT: 8080
      SEARXNG_LIMITER: false
      SEARXNG_VALKEY_URL: valkey://:s3cr3t@valkey:6379/0
    volumes:
      - .volumes/searxng/core-config:/etc/searxng/:Z
      - .volumes/searxng/core-data:/var/cache/searxng/
